### PR TITLE
Tweak pre-release detection.

### LINKED ISSUE #25: Release "v1.2.0-alpha-20220328" incorrectly generated an issue
https://github.com/pulumi/pulumi-terraform/issues/658

### PR DESCRIPTION
**Pull request by jkodroff**
Fixes #25

### CODE REVIEW

File: lambda/main.go [hunk 1]
```diff
@@ -162,6 +162,7 @@ func isPreRelease(version string) bool {
 	terms := []string{
 		"pre",
 		"beta",
+		"alpha",
```
Comment (viveklak) [inline lambda/main.go:165]: Curious if we should just use one of the semver libraries instead, like https://github.com/blang/semver?

**Review by viveklak — APPROVED** [review]
